version: "3"
services:
  kibana:
    build:
      context: kibana
    environment:
      #      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
     - 5601:5601
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
